{{- if .Values.metrics.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "witwave-operator.fullname" . }}-metrics
  labels:
    {{- include "witwave-operator.labels" . | nindent 4 }}
    control-plane: controller-manager
spec:
  type: ClusterIP
  selector:
    {{- include "witwave-operator.selectorLabels" . | nindent 4 }}
  ports:
    - name: {{ ternary "https" "http" .Values.metrics.secure }}
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
{{- end }}
