{{- range .Values.agents }}
{{- if .config }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-{{ .name }}-config
  labels:
    {{- include "nyx.agentLabels" .name | nindent 4 }}
data:
{{- range .config }}
  {{ .name }}: |
    {{- .content | nindent 4 }}
{{- end }}
{{- end }}
{{- $agentName := .name }}
{{- range .backends }}
{{- if .config }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-{{ $agentName }}-{{ .name }}-config
  labels:
    {{- include "nyx.backendLabels" (dict "agentName" $agentName "backendName" .name) | nindent 4 }}
data:
{{- range .config }}
  {{ .name }}: |
    {{- .content | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
