{{- range .Values.agents }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
  labels:
    {{- include "nyx.agentLabels" .name | nindent 4 }}
  {{- if ((.metrics).enabled | default $.Values.metrics.enabled) }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .port | default 8000 | quote }}
    prometheus.io/path: "/metrics"
  {{- end }}
spec:
  type: {{ ((.service).type) | default "ClusterIP" }}
  selector:
    app.kubernetes.io/name: {{ .name }}
  ports:
    - name: http
      port: {{ .port | default 8000 }}
      targetPort: {{ .port | default 8000 }}
{{- end }}
