{{- range .Values.agents }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
  labels:
    {{- include "nyx.agentLabels" .name | nindent 4 }}
  {{- if ((.metrics).enabled | default $.Values.metrics.enabled) }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"
  {{- end }}
spec:
  selector:
    app.kubernetes.io/name: {{ .name }}
  ports:
    - name: http
      port: 8000
      targetPort: 8000
{{- end }}
